# Generated by Django 4.2.6 on 2024-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_activity', '0007_alter_core_ign_engineer_alter_core_internet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='zabbix_maintenance_id',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='core',
            name='tickets_zendesk_generated',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
