# Generated by Django 4.2.6 on 2024-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_activity', '0008_core_zabbix_maintenance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='zabbix_maintenance_id',
            field=models.CharField(max_length=6),
        ),
    ]
