# Generated by Django 4.2.6 on 2023-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_registration',
            name='circuito',
            field=models.CharField(max_length=6),
        ),
    ]
