# Generated by Django 4.2.6 on 2023-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_activity', '0002_alter_troubleshooting_registration_circuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_registration',
            name='circuito',
            field=models.CharField(max_length=20),
        ),
    ]
