# Generated by Django 4.2.6 on 2023-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_activity', '0005_core_downtime_alter_core_description_to_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='downtime',
            field=models.TextField(default='', max_length=6, verbose_name='Downtime who will send to customer'),
        ),
    ]
